import { Employee } from '../../core/models/employee.model';

export const MOCK_EMPLOYEES: Employee[] = [
  { id: '1', firstName: 'James',  lastName: 'Wilson',  phone: '+1 555-0101', description: 'Board-certified cardiologist with 12 years of clinical experience. Specializes in interventional cardiology and heart failure management.',          role: 'EMPLOYEE', isActive: true,  userId: 'm1', organizationId: 'mock', positionId: 'p1', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm1', email: 'j.wilson@medcrm.com'  }, position: { id: 'p1', name: 'Cardiology',       organizationId: 'mock', permissions: [] } },
  { id: '2', firstName: 'Amara',  lastName: 'Okafor',  phone: '+1 555-0102', description: 'Dermatologist with expertise in medical and cosmetic dermatology. Focused on skin cancer prevention and treatment of chronic skin conditions.',           role: 'EMPLOYEE', isActive: true,  userId: 'm2', organizationId: 'mock', positionId: 'p2', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm2', email: 'a.okafor@medcrm.com'  }, position: { id: 'p2', name: 'Dermatology',      organizationId: 'mock', permissions: [] } },
  { id: '3', firstName: 'Raj',    lastName: 'Patel',   phone: '+1 555-0103', description: 'Neurologist specializing in epilepsy and movement disorders. Over 8 years of experience diagnosing and treating complex neurological conditions.',        role: 'EMPLOYEE', isActive: true,  userId: 'm3', organizationId: 'mock', positionId: 'p3', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm3', email: 'r.patel@medcrm.com'   }, position: { id: 'p3', name: 'Neurology',        organizationId: 'mock', permissions: [] } },
  { id: '4', firstName: 'Lisa',   lastName: 'Park',    phone: '+1 555-0104', description: 'Pediatrician dedicated to providing comprehensive care for children from newborns to adolescents. Strong focus on developmental health and vaccination.',   role: 'EMPLOYEE', isActive: true,  userId: 'm4', organizationId: 'mock', positionId: 'p4', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm4', email: 'l.park@medcrm.com'    }, position: { id: 'p4', name: 'Pediatrics',       organizationId: 'mock', permissions: [] } },
  { id: '5', firstName: 'Maria',  lastName: 'Santos',  phone: '+1 555-0105', description: 'Orthopedic surgeon with a focus on sports medicine and joint replacement. Helps patients recover mobility and quality of life after injuries.',             role: 'EMPLOYEE', isActive: false, userId: 'm5', organizationId: 'mock', positionId: 'p5', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm5', email: 'm.santos@medcrm.com'  }, position: { id: 'p5', name: 'Orthopedics',      organizationId: 'mock', permissions: [] } },
  { id: '6', firstName: 'Henrik', lastName: 'Larsson', phone: '+1 555-0106', description: 'General practitioner with a holistic approach to patient care. Experienced in managing chronic diseases, preventive care, and routine health check-ups.', role: 'EMPLOYEE', isActive: true,  userId: 'm6', organizationId: 'mock', positionId: 'p6', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm6', email: 'h.larsson@medcrm.com' }, position: { id: 'p6', name: 'General Practice', organizationId: 'mock', permissions: [] } },
  { id: '7', firstName: 'Yuki',   lastName: 'Tanaka',  phone: '+1 555-0107', description: 'Cardiologist with special interest in electrophysiology and arrhythmia management. Conducts research in non-invasive cardiac diagnostics.',               role: 'EMPLOYEE', isActive: true,  userId: 'm7', organizationId: 'mock', positionId: 'p1', createdAt: '', updatedAt: '', deletedAt: null, user: { id: 'm7', email: 'y.tanaka@medcrm.com'  }, position: { id: 'p1', name: 'Cardiology',       organizationId: 'mock', permissions: [] } },
];
